<a href="https://colab.research.google.com/github/SherlynVironica/PSDS-Mahir-7.0/blob/main/PSDS_Mahir_7_0_Principal_Component_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
#inputkan data
A = np.matrix([[1,2,3,4],[5,5,6,7],[1,4,2,3],[5,3,2,1],[8,1,2,2]])

In [3]:
df = pd.DataFrame(A,columns=['a1','a2','a3','a4'])
df

a1  a2  a3  a4
0   1   2   3   4
1   5   5   6   7
2   1   4   2   3
3   5   3   2   1
4   8   1   2   2

In [4]:
df.mean()

a1    4.0
a2    3.0
a3    3.0
a4    3.4
dtype: float64

In [5]:
std_dev = np.std(df)
std_dev

a1    2.683282
a2    1.414214
a3    1.549193
a4    2.059126
dtype: float64

In [6]:
# Menginstansiasikan scaler
scaler = StandardScaler()

# Melatih scaler pada dataset
scaler.fit(df)

# Mentransformasi dataset
df_scaled = scaler.transform(df)

print(df_scaled)

[[-1.11803399 -0.70710678  0.          0.29138576]
 [ 0.372678    1.41421356  1.93649167  1.74831455]
 [-1.11803399  0.70710678 -0.64549722 -0.19425717]
 [ 0.372678    0.         -0.64549722 -1.16554303]
 [ 1.49071198 -1.41421356 -0.64549722 -0.6799001 ]]


In [7]:
dff = pd.DataFrame(df_scaled,columns=['a1','a2','a3','a4'])
dff

a1        a2        a3        a4
0 -1.118034 -0.707107  0.000000  0.291386
1  0.372678  1.414214  1.936492  1.748315
2 -1.118034  0.707107 -0.645497 -0.194257
3  0.372678  0.000000 -0.645497 -1.165543
4  1.490712 -1.414214 -0.645497 -0.679900

In [8]:
#mean data yang sudah dinormalkan
dff.mean()

a1   -4.440892e-17
a2    0.000000e+00
a3   -4.440892e-17
a4    0.000000e+00
dtype: float64

In [9]:
#mencari varians yang dijadikan diagonal
var = np.var(dff)
var

a1    1.0
a2    1.0
a3    1.0
a4    1.0
dtype: float64

In [10]:
cov = np.cov(dff.T, ddof=0) #ddf digunakan untuk menghitung matriks dengan derajat kebebasan 0
cov

array([[ 1.        , -0.31622777,  0.04811252, -0.18098843],
       [-0.31622777,  1.        ,  0.63900965,  0.61812254],
       [ 0.04811252,  0.63900965,  1.        ,  0.94044349],
       [-0.18098843,  0.61812254,  0.94044349,  1.        ]])

In [11]:
dff.T

0         1         2         3         4
a1 -1.118034  0.372678 -1.118034  0.372678  1.490712
a2 -0.707107  1.414214  0.707107  0.000000 -1.414214
a3  0.000000  1.936492 -0.645497 -0.645497 -0.645497
a4  0.291386  1.748315 -0.194257 -1.165543 -0.679900

In [13]:
#mencari nilai eigen dan vektor eigen
eigenvalues, eigenvectors = np.linalg.eig(cov)
print("Nilai Eigen:")
print(eigenvalues)
print("\nVektor Eigen:")
print(eigenvectors)

Nilai Eigen:
[2.51579324 1.0652885  0.39388704 0.02503121]

Vektor Eigen:
[[ 0.16195986 -0.91705888 -0.30707099  0.19616173]
 [-0.52404813  0.20692161 -0.81731886  0.12061043]
 [-0.58589647 -0.3205394   0.1882497  -0.72009851]
 [-0.59654663 -0.11593512  0.44973251  0.65454704]]


In [14]:
#Transformasikan kembali matriks dengan cara mengalikan matriks dengan vektor eigen dari lamda yang dipilih

import numpy as np
a = df_scaled
b = np.matrix([
    [0.16195986, -0.91705888],
    [-0.52404813, 0.20692161],
    [-0.58589647, -0.3205394],
    [-0.59654663, -0.11593512]])
c = np.dot(a,b)
c

matrix([[ 1.56561657e-02,  8.45205481e-01],
        [-2.85829189e+00, -8.72549255e-01],
        [-5.75566079e-02,  1.40104719e+00],
        [ 1.13385419e+00,  2.66998767e-04],
        [ 1.76633814e+00, -1.37397042e+00]])

In [15]:
#mencari PCA secara langsung
pca = PCA(n_components=2)
pr = pca.fit_transform(dff)
prf = pd.DataFrame(data=pr,columns=["a1","a2"])
prf

a1        a2
0 -0.015656  0.845205
1  2.858292 -0.872549
2  0.057557  1.401047
3 -1.133854  0.000267
4 -1.766338 -1.373970